### ISSUE TITLE
Redundant calls to data()?

### ISSUE THREAD

**Issue by joaander** [mphowardlab/neighbor#26]
https://github.com/mphowardlab/neighbor/blob/ad0cc7708fded69112d7723ba8be2d7dccbeba49/include/neighbor/LBVHTraverser.h#L435-L439

Are these two calls to `data()` redundant?

Compiling HOOMD, I get this compiler warning:
```
/hoomd/hoomd/extern/neighbor/include/neighbor/LBVHTraverser.h:435:20: warning: variable ‘clbvh’ set but not used [-Wunused-but-set-variable]
  435 |     LBVHCompressedData clbvh = data();
```

**Comment by mphoward** [comment]
Oops, yes, that is redundant. There is very little overhead to calling `data()` twice because it is just packing up pointers:

https://github.com/mphowardlab/neighbor/blob/ad0cc7708fded69112d7723ba8be2d7dccbeba49/include/neighbor/LBVHTraverser.h#L344-L353

But this should be fixed by replacing `data()` on line 439 by `clbvh` for readability.

**Comment by joaander** [comment]
That's what I thought. This warning just showed up as I was working on enabling and silencing more warnings in HOOMD builds.
